name: pylint

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pylint==2.11.1 aiohttp==3.7.4.post0
    - name: Analysing...
      id: main
      working-directory: ./
      run: |
        python3 -m pylint --rcfile=./.pylintrc cevlib/*.py cevlib/*/*.py --disable=fixme
      continue-on-error: false
